import os
print('Menginstal modul...')
os.system('python --version')
os.system('python -m pip install --upgrade pip')
os.system('pip install requests')
os.system('pip install colorama')
os.system('pip install bs4')
os.system('pip install beautifulsoup4')
os.system('pip install Anime')
os.system('pip install selenium')
os.system('pip install pyautogui')
os.system('pip install keyboard')
os.system('pip install input')
os.system('pip install pystyle')
os.system('pip install cursor')
